name: "Init emulators"
description: "Init android emulators"

inputs:
  emulator:
    description: "Emulator name"
    default: Pixel_8_API_32
    required: false
  copies:
    description: "Copies of emulator"
    default: "1"
runs:
  using: "composite"

  steps:
    - name: Init emulators
      continue-on-error: false
      run: |
        rm -r /Users/dev/.android/avd/
        mkdir -p /Users/dev/.android/avd/
        for i in {1..${{ inputs.copies }}}; do
        cp ${{ github.action_path }}/android/${{ inputs.emulator }}.ini /Users/dev/.android/avd/${{ inputs.emulator }}_${i}.ini
        done
        cp -R ${{ github.action_path }}/android/avd/ /Users/dev/.android/avd/
      shell: bash