name: "Get seconds from date"
description: "Get seconds from date"

inputs:
  from-date:
    description: "Date in seconds from epoch"
    required: true

outputs:
  hours-from-date:
    description: "Seconds from input.from-date"
    value: ${{ steps.calculations.outputs.hours-value }}
  minutes-from-date:
    description: "Seconds from input.from-date"
    value: ${{ steps.calculations.outputs.minutes-value }}
  seconds-from-date:
    description: "Seconds from input.from-date"
    value: ${{ steps.calculations.outputs.seconds-value }}

runs:
  using: "composite"
  steps:
    - id: calculations
      shell: bash
      run: |
          now_date=$(date +%s)

          runtime=$((now_date-${{inputs.from_date}}))

          hours=$((runtime / 3600))
          minutes=$(( (runtime % 3600) / 60))
          seconds=$((runtime))

          echo "hours-value=${hours}" >> $GITHUB_OUTPUT
          echo "minutes-value=${minutes}" >> $GITHUB_OUTPUT
          echo "seconds-value=${seconds}" >> $GITHUB_OUTPUT

