name: "Setup environment (ruby dependencies)"
description: "Install all dependencies (Gemfile)"

runs:
  using: "composite"
  steps:
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true
    - name: Configure bundler
      run: bundle config set --local path 'vendor/bundle'
      shell: bash
    - name: Install gems
      run: bundle install
      shell: bash
