name: "Upload to artifactory"
description: "Upload to artifactory"

inputs:
  artifactory-url:
    description: "URL"
    required: true
  artifactory-user:
    description: "username"
    required: true
  artifactory-token:
    description: "token"
    required: true
  artifactory-project:
    description: "project"
    required: true
  artifactory-slug:
    description: "slug"
    required: true
  what-to-archive:
    description: "filename or path to folder"
    required: true
  filename-in-artifactory:
    description: "filename for artifactory"
    default: "artifact"

runs:
  using: "composite"
  steps:
    - name: Upload to artifactory
      shell: bash
      run: |
        FILE_TO_UPLOAD=""

        if [[ -d ${{inputs.what-to-archive}} ]]; then
          # we need to zip foler into archive
          if [[ ${{inputs.filename-in-artifactory}} == *.zip ]];
          then
            # no add extension
            FILE_TO_UPLOAD=${{inputs.filename-in-artifactory}}
          else
            # add extension
            FILE_TO_UPLOAD=${{inputs.filename-in-artifactory}}.zip
          fi
          zip -r $FILE_TO_UPLOAD ${{inputs.what-to-archive}}
        elif [[ -f ${{inputs.what-to-archive}} ]]; then
          # we need to upload file itself
          cp ${{inputs.what-to-archive}} ${{inputs.filename-in-artifactory}}
          FILE_TO_UPLOAD=${{ inputs.filename-in-artifactory }}
        else
            echo "ERROR: ${{inputs.what-to-archive}} is not valid file or directory name"
            echo "ERROR: Please, check if file exists from previous step!!!"
            exit 0
        fi        

        CURRENT_DATE=$(date +"%Y%m%d%H%M%S")
        ARTIFACTORY_FILE=${{ inputs.artifactory-url }}/${{ inputs.artifactory-project }}/${{ inputs.artifactory-slug }}/$CURRENT_DATE/$FILE_TO_UPLOAD
        curl -u${{ inputs.artifactory-user }}:${{ inputs.artifactory-token }} \
          -X PUT -v \
          -T $FILE_TO_UPLOAD \
          $ARTIFACTORY_FILE

        rm $FILE_TO_UPLOAD
 
        echo "Artifactory URL is:  $ARTIFACTORY_FILE" >> $GITHUB_STEP_SUMMARY
