name: "Upload to artifactory"

inputs:
  artifactory-url:
    description: "URL"
    required: true
  artifactory-user:
    description: "username"
    required: true
  artifactory-token:
    description: "token"
    required: true
  artifactory-project:
    description: "project"
    required: true
  artifactory-slug:
    description: "slug"
    required: true
  what_to_archive:
    description: "filename or path to folder"
    required: true
  filename_in_artifactory:
    description: "filename for artifactory"
    default: "artifact"

runs:
  using: "composite"
  steps:
    - name: Upload to artifactory
      shell: bash
      run: |
        FILE_TO_UPLOAD=${{inputs.filename_in_artifactory}}.zip
        zip -r $FILE_TO_UPLOAD ${{inputs.what_to_archive}}

        CURRENT_DATE=$(date +"%Y%m%d%H%M%S")
        ARTIFACTORY_FILE=${{ inputs.artifactory-url }}/${{ inputs.artifactory-project }}/${{ inputs.artifactory-slug }}/$CURRENT_DATE/$FILE_TO_UPLOAD
        curl -u${{ env.ARTIFACTORY_USERNAME }}:${{ env.ARTIFACTORY_TOKEN }} \
          -X PUT -v \
          -T $FILE_TO_UPLOAD \
          $ARTIFACTORY_FILE

        rm -rf $FILE_TO_UPLOAD

        echo "Artifactory URL is:  $ARTIFACTORY_FILE" >> $GITHUB_STEP_SUMMARY
