name: Cancel previous runs

on:
  workflow_call:
    secrets:
      github_access_token:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cancel_previous_runs:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-20.04
    steps:
      - uses: styfle/cancel-workflow-action@0.12.0
        with:
          all_but_latest: true
          access_token: ${{ secrets.github_access_token }}
