name: Check pull request

on:
  workflow_call:
    secrets:
      github_access_token:
        required: true
      security_scan_url:
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cancel_previous_runs:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true
          access_token: ${{ secrets.github_access_token }}

  check_pr:
    needs: cancel_previous_runs
    name: 'Check pull request'
    runs-on: ubuntu-latest
    if: github.event_name  == 'pull_request'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.1.0
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.6'
      - name: Install ruby dependencies
        run: |
          if test -f "Gemfile"; then
            bundle lock --add-platform x86_64-linux
            bundle config set --local path 'vendor/bundle'
            bundle install
          fi
      - uses: MeilCli/danger-action@v5
        continue-on-error: true
        with:
          plugins_file: 'Gemfile'
          danger_file: 'Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.github_access_token }}

  security_scan:
    needs: cancel_previous_runs
    name: 'Security scan'
    runs-on: [self-hosted,security,scan]
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    steps:
      - name: Run security scan horusec
        run: curl --connect-timeout 600 --max-time 900 -X POST "${{secrets.security_scan_url}}/scan?task_name=horusec_sast&ssh_repo_key=git@github.com:${{github.repository}}.git"
      - name: Run security scan semgrep secrets
        run: curl --connect-timeout 600 --max-time 900 -X POST "${{secrets.security_scan_url}}/scan?task_name=semgrep_secrets&ssh_repo_key=git@github.com:${{github.repository}}.git"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run security scan owasp
        run: if test -f "build.gradle"; then curl --connect-timeout 600 --max-time 900 -X POST "${{secrets.security_scan_url}}/scan?task_name=owasp_dependency_scan&ssh_repo_key=git@github.com:${{github.repository}}.git"; fi
      - name: Run security scan semgrep java-kotlin
        run: if test -f "build.gradle"; then curl --connect-timeout 600 --max-time 900 -X POST "${{secrets.security_scan_url}}/scan?task_name=semgrep_java_kotlin_sast&ssh_repo_key=git@github.com:${{github.repository}}.git"; fi
      - name: Run security scan snyk
        run: if test -f "Podfile" || test -f "Gemfile" || test -f "Gemfile.lock "|| test -f "Podfile.lock"; then curl --connect-timeout 600 --max-time 900 -X POST "${{secrets.security_scan_url}}/scan?task_name=snyk_dependency_scan&ssh_repo_key=git@github.com:${{github.repository}}.git"; fi
