name: Check pull request

on:
  workflow_call:
    secrets:
      github_access_token:
        required: true

jobs:
  check_pr:
    name: 'Check pull request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true
      - run: bundle config set --local path 'vendor/bundle'
      - uses: MeilCli/danger-action@v5
        with:
          plugins_file: 'Gemfile'
          danger_file: 'Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.github_access_token }}
