name: Check pull request

on:
  workflow_call:
    secrets:
      github_access_token:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_pr:
    runs-on: ubuntu-latest
    if: github.event_name  == 'pull_request'
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true
          access_token: ${{ secrets.github_access_token }}

      - name: Checkout repo
        uses: actions/checkout@v3.1.0

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.6'

      - name: Install ruby dependencies
        run: |
          if test -f "Gemfile"; then
            bundle lock --add-platform x86_64-linux
            bundle config set --local path 'vendor/bundle'
            bundle install
          fi

      - uses: MeilCli/danger-action@v5
        continue-on-error: true
        with:
          plugins_file: 'Gemfile'
          danger_file: 'Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.github_access_token }}
