name: Check pull request

on:
  workflow_call:
    secrets:
      github_access_token:
        required: true
      maven_readonly_token:
        required: true

env:
  MAVEN_READONLY_TOKEN: ${{ secrets.maven_readonly_token }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        runs-on: ubuntu-latest
        steps:
          - uses: styfle/cancel-workflow-action@0.11.0
            with:
              all_but_latest: true
              access_token: ${{ secrets.github_access_token }}

      - name: Checkout repo
        uses: actions/checkout@v3.1.0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Run detekt
        if: success() || failure()
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detekt

      - name: Setup ruby
        if: success() || failure()
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.6'
          bundler-cache: true

      - name: Run Danger
        if: success() || failure()
        run: |
          gem install danger
          bundle exec danger --dangerfile=Dangerfile --danger_id=danger-pr
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.github_access_token }}