name: Run Android UI tests

on:
  workflow_call:
    inputs:
      is_gradle_cache_debug_enabled:
        description: "Enable or disable Gradle build cache"
        type: boolean
        default: true
        required: false
      flank_configuration_file:
        description: "Path to Flank configuration"
        type: string
        default: "./ci/flank/pr_tests_config.yml"
        required: false
    secrets:
      github_access_token:
        required: true
      ssh_private_key:
        required: false
      maven_readonly_token:
        required: true
      firebase_key:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cancel_previous_runs:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true
          access_token: ${{ secrets.github_access_token }}
  run_ui_tests:
    name: UI tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Assemble
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleDebug assembleDebugAndroidTest
          cache-read-only: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/main' && github.ref != 'refs/heads/release' && github.ref != 'refs/heads/develop' }}
        env:
          MAVEN_READONLY_TOKEN: ${{ secrets.maven_readonly_token }}
          GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: ${{ inputs.is_gradle_cache_debug_enabled }}
      - name: Upload sample debug APK
        uses: actions/upload-artifact@v3
        with:
          name: sample_app-debug
          path: sample_app/build/outputs/apk/debug/sample_app-debug.apk
      - name: Upload androidTest APK
        uses: actions/upload-artifact@v3
        with:
          name: sample_app-debug-androidTest
          path: sample_app/build/outputs/apk/androidTest/debug/sample_app-debug-androidTest.apk
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Run instrumented tests
        uses: Flank/flank@master
        with:
          service_account: ${{ secrets.firebase_key }}
          platform: android
          flank_configuration_file: ${{ inputs.flank_configuration_file }}
