name: Run Android UI tests

on:
  workflow_call:
    inputs:
      is_gradle_cache_debug_enabled:
        description: "Enable or disable Gradle build cache"
        type: boolean
        default: true
        required: false
      flank_configuration_file:
        description: "Path to Flank configuration"
        type: string
        default: "./ci/flank/pr_tests_config.yml"
        required: false
      assemble_task:
        type: string
        default: "assembleDebug"
        required: true
        description: "Gradle task to build target app APK"
      assemble_android_test_task:
        type: string
        default: "assembleDebugAndroidTest"
        required: true
        description: "Gradle task to build target AndroidTest APK"
      output_apk_build_path:
        type: string
        default: "sample_app/build/outputs/apk/debug/sample_app-debug.apk"
        required: true
        description: "Path to target app APK"
      output_test_apk_build_path:
        type: string
        default: "sample_app/build/outputs/apk/androidTest/debug/sample_app-debug-androidTest.apk"
        required: true
        description: "Path to target app APK"
      uploaded_app_artifact_name:
        type: string
        default: "sample_app-debug"
        required: true
        description: "Name of the folder where app artifact was uploaded"
      uploaded_test_artifact_name:
        type: string
        default: "sample_app-debug-androidTest"
        required: true
        description: "Name of thr folder where test artifact was uploaded"
    secrets:
      github_access_token:
        required: true
      ssh_private_key:
        required: false
      maven_readonly_token:
        required: true
      firebase_key:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_ui_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true
          access_token: ${{ secrets.github_access_token }}

      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Assemble
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ inputs.assemble_task }} ${{ inputs.assemble_android_test_task }}
          cache-read-only: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/main' && github.ref != 'refs/heads/release' && github.ref != 'refs/heads/develop' }}
        env:
          MAVEN_READONLY_TOKEN: ${{ secrets.maven_readonly_token }}
          GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: ${{ inputs.is_gradle_cache_debug_enabled }}

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.uploaded_app_artifact_name }}
          path: ${{ inputs.output_apk_build_path }}

      - name: Upload androidTest APK
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.uploaded_test_artifact_name }}
          path: ${{ inputs.output_test_apk_build_path }}

      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Run instrumented tests
        uses: Flank/flank@v23.04.0
        with:
          service_account: ${{ secrets.firebase_key }}
          platform: android
          flank_configuration_file: ${{ inputs.flank_configuration_file }}