name: Swiftlint

on:
  workflow_call:
    inputs:
      paths:
        description: 'Paths for linting folders from root separated by comma'
        default: ""
        type: string
        required: true
      is_strict:
        description: 'Any lint warnings will be determine as error'
        default: false
        type: boolean
        required: false
      is_quiet:
          description: 'If true disable logging, like \"Linting...\" message'
          default: true
          type: boolean
          required: false
      config_path:
        description: 'Custom base path for swiftlint configuration file. Config search will be performed on the root if path does not specified'
        default: ""
        type: string
        required: false
    secrets:
      github_access_token:
        required: true
      ssh_private_key:
        required: true
jobs:
  linter:
    runs-on: macos-12
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Setup SSH
      uses: tutu-ru-mobile/gh-actions-setup-ssh@v1
      with:
        ssh-private-key: ${{ secrets.ssh_private_key }}
    - name: Sync SwiftLint version
      run: ./download_project_utils.sh
    - name: Run SwiftLint
      run: |
        SWIFTLINT_DIR="vendor/etc/bin/swiftlint"

        url=https://api.github.com/repos/$GITHUB_REPOSITORY/compare/$GITHUB_BASE_REF...$GITHUB_HEAD_REF
        echo "Get file diffs from $url"
        CHANGED_FILES=$( \
        curl -H "Accept: application/vnd.github.v3.diff" -H "Authorization: token ${{ secrets.github_access_token }}" $url \
            | { grep -E '^diff --git (a\/.+.swift) (b\/.+.swift)$' || :; } \
            | awk '{print substr($4,3)}'
            )
        if [ -z "$CHANGED_FILES" ]; then
          echo "Nothing to lint"
          exit 0
        fi
        
        paths_list=$(echo ${{ inputs.paths }} | awk -F ',' '{ for( i=1; i<=NF; i++ ) print $i }' )
        linter_errors=""
        for path in ${paths_list[@]}; do
            last_path=$(echo $path | awk -F "/" '{print $NF}')

            origin_config_name=".$last_path.swiftlint.yml"
            origin_config_path=$origin_config_name
            if [ ! -z ${{ inputs.config_path }} ]; then
              origin_config_path="${{ inputs.config_path }}/$origin_config_path"
            fi
      
            # - start temp config setup -
            # Исключаем нарушения todo (пока не придумано лучшее решение)
            temp_config=$origin_config_name.tmp
            rm -f $temp_config
            touch $temp_config
            echo -e "parent_config: $origin_config_path\n\ndisabled_rules:\n    - todo" >> $temp_config
            # - done temp config setup -

            source_dir=$path
            filtered=$( for file in ${CHANGED_FILES[@]}; do echo $file; done | { grep -E "^$source_dir/" || :; } )
            filtered=$( for file in ${filtered[@]}; do if [ -f $file ]; then echo $file; fi done )
            config_args=""

            if [ -n "$filtered" ]; then
                echo "Run SwiftLint ($($SWIFTLINT_DIR/swiftlint --version)) using $temp_config"
                config_args=""
                if [ ${{ inputs.is_strict }} == true ]; then
                  config_args+="--strict "
                fi
                if [ ${{ inputs.is_quiet }} == true ]; then
                  config_args+="--quiet "
                fi

                config_args+="--reporter emoji "
                config_args+="--config $temp_config "
                echo "Run with args $config_args"
                lint_result=$($SWIFTLINT_DIR/swiftlint $config_args $filtered)
                if [[ -n "$lint_result" ]]; then
                  linter_errors+="$lint_result\n"
                fi
            else
                echo "Nothing to lint for $source_dir. Skip it"
            fi

            rm $temp_config
        done

        echo "All done"
        if [[ -n "$linter_errors" ]]; then
          echo "❗️ There are some linter warnings/errors. Please, fix it and try again ❗️"
          echo "$linter_errors"
          exit 2
        fi
