name: Run Android Unit tests

on:
  workflow_call:
    inputs:
      is_gradle_cache_debug_enabled:
        description: "Enable or disable Gradle build cache"
        type: boolean
        default: true
        required: false
    secrets:
      github_access_token:
        required: true
      ssh_private_key:
        required: false
      maven_readonly_token:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_unit_tests:
    runs-on: tutu-mac-builder
    defaults:
      run:
        shell: bash -leo pipefail {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean gradle cache
        run: ./gradlew clean
        env:
          MAVEN_READONLY_TOKEN: ${{ secrets.maven_readonly_token }}

      - name: Run unit tests
        run: ./gradlew test --no-daemon
        env:
          MAVEN_READONLY_TOKEN: ${{ secrets.maven_readonly_token }}
          GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: ${{ inputs.is_gradle_cache_debug_enabled }}
