name: Run security scan

on:
  workflow_call:
    secrets:
      github_access_token:
        required: true
      security_scan_url:
        required: true

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security_scan:
    name: 'Security scan'
    runs-on: [self-hosted,security,scan]
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    steps:
      - name: Run security scan horusec
        run: curl --connect-timeout 600 --max-time 900 -X POST "${{secrets.security_scan_url}}/scan?task_name=horusec_sast&ssh_repo_key=git@github.com:${{github.repository}}.git"
      - name: Run security scan semgrep secrets
        run: curl --connect-timeout 600 --max-time 900 -X POST "${{secrets.security_scan_url}}/scan?task_name=semgrep_secrets&ssh_repo_key=git@github.com:${{github.repository}}.git"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run security scan owasp
        run: if test -f "build.gradle"; then curl --connect-timeout 600 --max-time 900 -X POST "${{secrets.security_scan_url}}/scan?task_name=owasp_dependency_scan&ssh_repo_key=git@github.com:${{github.repository}}.git"; fi
      - name: Run security scan semgrep java-kotlin
        run: if test -f "build.gradle"; then curl --connect-timeout 600 --max-time 900 -X POST "${{secrets.security_scan_url}}/scan?task_name=semgrep_java_kotlin_sast&ssh_repo_key=git@github.com:${{github.repository}}.git"; fi
      - name: Run security scan snyk
        run: if test -f "Podfile" || test -f "Gemfile" || test -f "Gemfile.lock "|| test -f "Podfile.lock"; then curl --connect-timeout 600 --max-time 900 -X POST "${{secrets.security_scan_url}}/scan?task_name=snyk_dependency_scan&ssh_repo_key=git@github.com:${{github.repository}}.git"; fi
