name: Run Record snapshots

on:
  workflow_call:
    inputs:
      is_run_xcodegen:
        description: '`true` is for run xcodegen'
        default: false
        type: boolean
        required: false
      workspace_name:
        description: 'Path to workspace file'
        type: string
        required: true
      scheme_name:
        description: 'Scheme name to run for record snapshots'
        type: string
        required: true
      xcresult_name:
        description: 'File bundle path to save xcresult'
        type: string
        required: true
    secrets:
      github_access_token:
        required: true
      ssh_private_key:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cancel_previous_runs:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true
          access_token: ${{ secrets.github_access_token }}
  record_snapshots:
    needs: cancel_previous_runs
    runs-on: macos-12
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,name=iPhone 11']
        swift: ["5.5"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Setup SSH
        uses: tutu-ru-mobile/github-action-ssh-agent@v1.0.0
        with:
          ssh-private-key: ${{ secrets.ssh_private_key }}
      - name: Change origin to ssh link
        run: git remote set-url origin git@github.com:$GITHUB_REPOSITORY.git
      - uses: tutu-ru-mobile/github-workflows/action_select_xcode_version@v1.0.4
      - uses: tutu-ru-mobile/github-workflows/action_install_dependencies@v1.0.4
      - uses: tutu-ru-mobile/github-workflows/action_restore_cache_cocoapods@v1.0.4
      - if: ${{ inputs.is_run_xcodegen }}
        name: Generate xcodeproj
        run: |
          make install-xcodegen
          make generate-xcodeproj
      - name: Remove snapshots
        run: find . -type d -name "__Snapshots__" -exec rm -rf {} +
      - name: Build and record Snapshots
        run: xcodebuild clean test -workspace ${{ inputs.workspace_name }} -scheme ${{ inputs.scheme_name }} -testLanguage ru -testRegion ru_RU -destination "${destination}" -resultBundlePath '${{ inputs.xcresult_name }}' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | bundle exec xcpretty
        env:
           destination: ${{ matrix.destination }}
      - name: Make PR with new snapshots
        uses: tutu-ru-mobile/create-pull-request@tutu
        with:
          branch: "feature/NO-ISSUE_recording_${{github.run_id}}"
          delete-branch: true
          token: ${{ secrets.github_access_token }}
          base: ${{ github.head_ref }}
          title: "NO-ISSUE: updated snapshots"
          body: >
              Updated snapshots 
          add-pattern-array: "**__Snapshots__**.png"
