name: Run version bump

on:
  workflow_call:
    inputs:
      bump_type:
        description: "What type of number will be bumped: patch|minor|major. Default is `patch`"
        default: "patch"
        type: string
        required: true
      is_run_fastlane:
        description: "Manual run or with fastlane lane. Default is `true`"
        default: true
        type: boolean
        required: true
    secrets:
      github_access_token:
        required: true
      ssh_private_key:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  bump:
    runs-on: tutu-mac-builder
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: bundle install
      - name: Change origin to ssh link
        run: git remote set-url origin git@github.com:$GITHUB_REPOSITORY.git
      - if: ${{ inputs.is_run_fastlane }}
        name: Bump
        # Исправление как в https://github.com/tutu-ru-mobile/ios-features/blob/fe81d704ff157dab5522c91bc0329bd4ea2de3ab/.github/workflows/bump.yml#L32-L35
        run: |
          for podspec in $(ls *.podspec | sed 's/.podspec$//'); do \
            echo "Deleting repository: $podspec" \
            && rm -rf ~/.cocoapods/repos/$podspec; \
          done \
          && bundle exec fastlane ${{ inputs.bump_type }}
