name: 'Run danger-kotlin'

on:
  workflow_call:
    secrets:
      github_access_token:
        required: true
      tutu_read_packages_token:
        required: true

env:
  TUTU_READ_PACKAGES_TOKEN: ${{ secrets.tutu_read_packages_token }}
  MAVEN_READONLY_TOKEN: ${{ secrets.tutu_read_packages_token }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -leo pipefail {0}
  
jobs:
  pull-request:
    runs-on: tutu-mac-builder
    steps:
      - uses: actions/checkout@v4

      - name: Copy detekt config
        uses: tutu-ru-mobile/github-workflows/action_copy_config@main
        with:
          file_path: 'config/detekt/detekt.yml'

      - name: Run detekt
        if: success() || failure()
        run: ./gradlew detekt

      - name: Copy Dangerfile
        uses: tutu-ru-mobile/github-workflows/action_copy_config@main
        with:
          file_path: 'Dangerfile.df.kts'
       
      - name: Danger
        run: danger-kotlin ci --failOnErrors --dangerfile Dangerfile.df.kts
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.github_access_token }}
