name: Run Record snapshots

on:
  workflow_call:
    inputs:
      is_run_xcodegen:
        description: '`true` is for run xcodegen'
        default: false
        type: boolean
        required: false
      workspace_name:
        description: 'Path to workspace file'
        type: string
        required: true
      scheme_name:
        description: 'Scheme name to run for record snapshots'
        type: string
        required: true
      xcresult_name:
        description: 'File bundle path to save xcresult'
        type: string
        required: true
      is_run_check:
        description: '`true` is for run check snapshots after record'
        default: false
        type: boolean
        required: false
    secrets:
      github_access_token:
        required: true
      ssh_private_key:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  record_xcresults_name: "RecordSnapshots.xcresult"

jobs:
  cancel_previous_runs:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-20.04
    steps:
      - uses: styfle/cancel-workflow-action@0.12.0
        with:
          all_but_latest: true
          access_token: ${{ secrets.github_access_token }}
  record_snapshots:
    needs: cancel_previous_runs
    runs-on: macos-12
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,name=iPhone 11']
        swift: ["5.5"]
    steps:
      - name: System info
        run: |
          echo "CPU arch" && arch
          system_profiler SPSoftwareDataType SPHardwareDataType
      - name: Checkout repository
        uses: actions/checkout@v3.1.0
      - name: Setup SSH
        uses: tutu-ru-mobile/github-action-ssh-agent@v1.1.0-tutu
        with:
          ssh-private-key: ${{ secrets.ssh_private_key }}
      - name: Change origin to ssh link
        run: git remote set-url origin git@github.com:$GITHUB_REPOSITORY.git
      - uses: tutu-ru-mobile/github-workflows/action_select_xcode_version@v1.0.5
      - uses: tutu-ru-mobile/github-workflows/action_install_dependencies@v1.0.5
      - uses: tutu-ru-mobile/github-workflows/action_restore_cache_cocoapods@v1.0.5
      - if: ${{ inputs.is_run_xcodegen }}
        name: Generate xcodeproj
        run: |
          make install-xcodegen
          make generate-xcodeproj
      - name: Remove snapshots
        run: find . -type d -name "__Snapshots__" -exec rm -rf {} +
      - run: touch .ci_tag
      - name: Build and record Snapshots (First run)
        timeout-minutes: 90
        continue-on-error: true
        run: |
            xcodebuild clean test \
            -workspace ${{ inputs.workspace_name }} \
            -scheme ${{ inputs.scheme_name }} \
            -skipUnavailableActions \
            -skipPackagePluginValidation \
            -testLanguage ru \
            -testRegion ru_RU \
            -destination "${destination}" \
            -resultBundlePath '${{ env.record_xcresults_name }}' \
            -retry-tests-on-failure \
            -test-iterations 5 \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            ONLY_ACTIVE_ARCH=NO \
            | bundle exec xcpretty
        env:
           destination: ${{ matrix.destination }}
      - if: ${{ inputs.is_run_check }}
        name: Check Snapshots (Second run)
        timeout-minutes: 90
        run: |
            xcodebuild test \
            -workspace ${{ inputs.workspace_name }} \
            -scheme ${{ inputs.scheme_name }} \
            -skipUnavailableActions \
            -skipPackagePluginValidation \
            -testLanguage ru \
            -testRegion ru_RU \
            -destination "${destination}" \
            -resultBundlePath '${{ inputs.xcresult_name }}' \
            -retry-tests-on-failure \
            -test-iterations 5 \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            ONLY_ACTIVE_ARCH=NO
        env:
           destination: ${{ matrix.destination }}
      - run: rm .ci_tag
      - name: Make PR with new snapshots
        uses: tutu-ru-mobile/create-pull-request@tutu
        with:
          branch: "feature/NO-ISSUE_recording_${{github.run_id}}"
          delete-branch: true
          token: ${{ secrets.github_access_token }}
          base: ${{ github.head_ref }}
          title: "NO-ISSUE: updated snapshots"
          body: >
              Updated snapshots 
          add-pattern-array: "**__Snapshots__**.png"
      - name: Save xcresult folders
        uses: actions/upload-artifact@v2
        with:
          name: Folders with xcresults
          path: |
            ${{ env.record_xcresults_name }}
            ${{ inputs.xcresult_name }}
          retention-days: 1
