name: Setup environment for macOS

on:
  workflow_call:
    secrets:
      github_access_token:
        required: true

jobs:
  cancel_previous_runs:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.10.0
        with:
          all_but_latest: true
          access_token: ${{ github_access_token }}