name: Check pull request

on:
  workflow_call:
    inputs:
      release_branch_pattern:
        description: 'Regex pattern for release branch. Like: release/(transport|avia|bus|train)-'
        type: string
        required: true
      failured_tests_data:
        description: "Directory in which failured tests logs are placed"
        type: string
        required: false
        default: ""
      show_tests_results:
        description: "Flag indicates that need to show failured tests logs"
        type: boolean
        required: false
    secrets:
      github_access_token:
        required: true
      ssh_private_key:
        required: true

defaults:
  run:
    shell: bash -leo pipefail {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_pr:
    runs-on: tutu-mac-builder
    if: github.event_name  == 'pull_request'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sync Dangerfile
        run: |
          ./download_project_utils.sh
          cp -f vendor/ProjectUtils/Scripts/Dangerfile.swift Dangerfile.swift

      - if: ${{ inputs.failured_tests_data != '' }}
        name: Download failured tests data
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.failured_tests_data }}

      - if: ${{ inputs.failured_tests_data != '' }}
        name: Unpack tests data
        run: |
          unzip ${{ inputs.failured_tests_data }}.zip
          if [ -d ${{ inputs.failured_tests_data }} ]; then
            echo "Failured tests data unzip successfully"
          else
            echo "Unzip tests data failured!"
          fi

      - name: Create diff file
        run: |
          URL=https://api.github.com/repos/$GITHUB_REPOSITORY/compare/$GITHUB_BASE_REF...$GITHUB_HEAD_REF
          curl -H "Accept: application/vnd.github.v3.diff" -H "Authorization: token ${{ secrets.github_access_token }}" $URL > diff.txt

      - name: Danger
        run: danger-swift ci --failOnErrors --dangerfile Dangerfile.swift
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.github_access_token }}
          DANGER_RELEASE_BRANCH_PATTERN: ${{ inputs.release_branch_pattern }}
          DANGER_FAILURED_TESTS_DIR: ${{ inputs.failured_tests_data }}
          DANGER_SHOW_TESTS_RESUILTS: ${{ inputs.show_tests_results }}
          DANGER_DIFF_FILE: "diff.txt"

      - if: always()
        name: Post
        run: |
          rm diff.txt
          rm -rf ${{ inputs.failured_tests_data }}.zip
          rm -rf ${{ inputs.failured_tests_data }}
